# Generated by Django 5.2.9 on 2025-12-08 15:38

import parcels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('_id', models.CharField(default=parcels.models.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(default=parcels.models.generate_tracking_number, max_length=100, unique=True)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_address', models.TextField(blank=True)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_address', models.TextField(blank=True)),
                ('current_status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('current_location_lat', models.FloatField(blank=True, null=True)),
                ('current_location_lng', models.FloatField(blank=True, null=True)),
                ('current_location_address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('status_history', models.TextField(default='[]')),
            ],
            options={
                'db_table': 'parcels',
                'ordering': ['-created_at'],
            },
        ),
    ]
