# Generated by Django 5.2.9 on 2025-12-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='package_contents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='package_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
