# Generated by Django 4.1.13 on 2025-11-29 19:05

from django.db import migrations, models
import djongo.models.fields
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('_id', models.CharField(default=pages.models.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('owner_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('metadata', djongo.models.fields.EmbeddedField(default=dict, model_container=pages.models.PageMetadata)),
                ('analytics', djongo.models.fields.EmbeddedField(default=dict, model_container=pages.models.PageAnalytics)),
            ],
            options={
                'db_table': 'pages',
                'ordering': ['-updated_at'],
            },
        ),
    ]
