# Generated by Django 5.2.8 on 2025-11-29 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.customer')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('warehouse_location', models.CharField(max_length=200)),
                ('reason_waiting', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.parcel')),
            ],
        ),
    ]
